Repository Arquisoft/viade_en1b, pull requests merged in 2020-03, with the labels that each got.

#39 Dev showing route
  src/App.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/myMap/MyMap.js
  src/store/reducers/RouteReducer.js
Labels: development

#52 Styling profile marcos
  package.json
  src/components/layout/navbar/NavBar.js
  src/components/user/myProfile/FriendList.css
  src/components/user/myProfile/FriendList.js
  src/components/user/myProfile/MyProfile.css
  src/components/user/myProfile/MyProfile.js
Labels: development, style

#59 MapCenter solved
  src/components/dashboard/myMap/MyMap.css
Labels: development

#55 Main menu
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/coding-related.md
  .github/ISSUE_TEMPLATE/documentation-related.md
  .github/ISSUE_TEMPLATE/feature--enhancements.md
  .github/ISSUE_TEMPLATE/styling-work.md
  package-lock.json
  package.json
  src/components/layout/navbar/NavBar.js
  src/components/layout/slideshow/SlideShow.css
  src/components/layout/slideshow/Slideshow.js
  src/components/routes/myRoutes/MyRoutes.css
  src/components/routes/myRoutes/MyRoutes.js
  src/components/routes/myRoutes/MyRoutes.module.css
  src/components/routes/routeDetails/RouteDetails.css
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/routeDetails/RouteDetails.module.css
  src/components/routes/routeList/RouteList.js
  src/components/routes/routeList/RouteList.module.css
  src/components/routing/Routing.js
  src/store/reducers/RouteReducer.js
Labels: development

#60 func_deleteRoute_shareRoute
  package-lock.json
  src/components/routes/myRoutes/MyRoutes.js
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/shareRoute/ShareRoute.css
  src/components/routes/shareRoute/ShareRoute.js
  src/components/routing/Routing.js
  src/store/actions/RouteActions.js
  src/store/reducers/RouteReducer.js
Labels: development

#64 Storing info
  package.json
  src/assets/exampleRoute.json
  src/components/routes/uploadRoute/UploadRoute.js
  src/solid/routes.js
  src/store/actions/RouteActions.js
Labels: development

#65 Manually routing solved
  src/components/dashboard/Dashboard.js
  src/components/routes/myRoutes/MyRoutes.js
  src/components/routes/shareRoute/ShareRoute.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routing/Routing.js
  src/components/user/myProfile/MyProfile.js
Labels: bug, development

#67 Added tests for the Slideshow component
  src/components/layout/navbar/tests/NavBar.test.js
  src/components/layout/slideshow/Slideshow.js
  src/components/layout/slideshow/tests/Slideshow.test.js
  src/components/routes/routeDetails/RouteDetails.js
Labels: testing

#73 RouteReducer tested
  src/store/actions/RouteActions.js
  src/store/reducers/RouteReducer.js
  src/store/reducers/tests/RouteReducer.test.js
Labels: testing

#74 Friendlist test done
  src/components/user/myProfile/tests/FriendList.test.js
Labels: testing

#75 Added test for the UploadRoute component
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/uploadRoute/UploadRoute.css
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/tests/UploadRoute.test.js
Labels: testing

#68 Settings dev
  src/components/layout/navbar/NavBar.js
  src/components/routing/Routing.js
  src/components/settings/Settings.css
  src/components/settings/Settings.js
Labels: development

#77 RouteSummary tested
  src/components/pageNotFound/PageNotFound.js
  src/components/pageNotFound/tests/PageNotFound.test.js
  src/components/routes/routeSummary/RouteSummary.js
  src/components/routes/routeSummary/tests/RouteSummary.test.js
  src/createStore.js
  src/index.js
  src/store/actions/RouteActions.js
  src/store/actions/tests/RouteActions.test.js
  src/store/reducers/RouteReducer.js
  src/store/reducers/tests/RouteReducer.test.js
  src/utils/index.js
Labels: testing

#80 Added footer with some links
  package.json
  src/App.js
  src/components/layout/footer/Footer.css
  src/components/layout/footer/Footer.js
Labels: testing

#81 Settings component tested
  src/components/layout/navbar/tests/NavBar.test.js
  src/components/layout/settings/Settings.css
  src/components/layout/settings/Settings.js
  src/components/layout/settings/tests/Settings.test.js
  src/components/routing/Routing.js
  src/components/settings/Settings.js
Labels: testing

#83 Testing MyMap
  src/components/dashboard/Dashboard.js
  src/components/dashboard/myMap/MyMap.js
  src/components/dashboard/myMap/tests/MyMap.test.js
  src/components/routing/Routing.js
Labels: testing

#82 Week work
  package.json
  src/App.js
  src/assets/exampleRoute.json
  src/components/dashboard/Dashboard.js
  src/components/dashboard/myMap/MyMap.js
  src/components/dashboard/myMap/tests/MyMap.test.js
  src/components/layout/footer/Footer.css
  src/components/layout/footer/Footer.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/tests/NavBar.test.js
  src/components/layout/settings/Settings.css
  src/components/layout/settings/Settings.js
  src/components/layout/settings/tests/Settings.test.js
  src/components/layout/slideshow/Slideshow.js
  src/components/layout/slideshow/tests/Slideshow.test.js
  src/components/pageNotFound/PageNotFound.js
  src/components/pageNotFound/tests/PageNotFound.test.js
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/routeDetails/tests/RouteDetails.test.js
  src/components/routes/routeSummary/RouteSummary.js
  src/components/routes/routeSummary/tests/RouteSummary.test.js
  src/components/routes/uploadRoute/UploadRoute.css
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/tests/UploadRoute.test.js
  src/components/routes/uploadRoute/uploadButton/UploadButton.js
  src/components/routes/uploadRoute/uploadButton/tests/UploadButton.test.js
  src/components/routing/Routing.js
  src/components/user/myProfile/tests/FriendList.test.js
  src/createStore.js
  src/index.js
  src/solid/routes.js
  src/store/actions/RouteActions.js
  src/store/actions/tests/RouteActions.test.js
  src/store/reducers/RouteReducer.js
  src/store/reducers/tests/RouteReducer.test.js
  src/utils/index.js
Labels: development

#86 Footer bug fixed
  src/components/layout/footer/Footer.css
Labels: bug

#87 Testing everything is ok
  src/components/layout/footer/Footer.css
  src/components/routes/routeList/RouteList.js
  src/components/routes/routeList/tests/RouteList.test.js
Labels: development

#89 Modal component
  src/components/layout/modal/Modal.css
  src/components/layout/modal/Modal.js
  src/components/layout/modal/tests/Modal.test.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/tests/UploadRoute.test.js
Labels: development

#90 App.js test
  src/App.js
  src/assets/Calendario de exámenes curso 2019-2020.pdf
  src/test/App.test.js
Labels: testing

#91 Testing cesar
  src/components/layout/footer/Footer.js
  src/components/layout/footer/tests/Footer.test.js
Labels: testing

#92 App test
  src/App.js
  src/assets/Calendario de exámenes curso 2019-2020.pdf
  src/test/App.test.js
Labels: testing

#79 Storing info
  src/docs/05_building_block_view.adoc
  src/solid/routes.js
  src/solid/tests/routes.test.js
  src/store/actions/RouteActions.js
Labels: development
