Repository Arquisoft/viade_en1b, pull requests merged in 2020-04, with the labels that each got.

#78 Fixed documentation source problems with header levels.
  src/docs/01_introduction_and_goals.adoc
  src/docs/05_building_block_view.adoc
Labels: documentation

#101 ShareRoutes tests are done
  src/components/layout/modal/Modal.js
  src/components/layout/modal/tests/Modal.test.js
  src/components/routes/shareRoute/ShareRoute.js
  src/components/routes/shareRoute/tests/ShareRoute.test.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/user/myProfile/FriendList.js
  src/middlewares/middlewares.js
  src/solid/routes.js
  src/store/reducers/RouteReducer.js
Labels: testing

#99 Tests
  package.json
  src/assets/check.svg
  src/assets/exampleRoute.json
  src/assets/sampleGPX.js
  src/assets/sampleGPX.txt
  src/components/dashboard/Dashboard.js
  src/components/dashboard/tests/Dashboard.test.js
  src/components/layout/footer/Footer.js
  src/components/layout/footer/test/Footer.test.js
  src/components/routing/utils/TestingRouter.js
  src/components/user/myProfile/FriendList.js
  src/components/user/myProfile/tests/FriendList.test.js
Labels: testing

#102 05_Building Block View
  package-lock.json
  src/components/layout/pageNotFound/PageNotFound.js
  src/components/layout/pageNotFound/tests/PageNotFound.test.js
  src/components/routing/Routing.js
  src/docs/03_system_scope_and_context.adoc
  src/docs/05_building_block_view.adoc
  src/docs/07_deployment_view.adoc
  src/docs/diagrams/05-01_whiteboxOverallSystem.puml
  src/docs/diagrams/05-02_whiteboxRedux.puml
  src/docs/diagrams/05-03_whiteboxSolid.puml
  src/docs/diagrams/05-04_whiteboxReact.puml
  src/docs/diagrams/05-05_whiteboxMiddlewares.puml
Labels: documentation

#103 I have updated documentation of part 4 and 3.1
  src/docs/03_system_scope_and_context.adoc
  src/docs/04_solution_strategy.adoc
  src/docs/11_technical_risks.adoc
Labels: documentation

#105 Documentation section 6 improved
  src/docs/06_runtime_view.adoc
  src/docs/build/docs/.asciidoctor/diagram/Sharing a route.png.cache
  src/docs/build/docs/.asciidoctor/diagram/Uploading a route.png.cache
  src/docs/build/docs/.asciidoctor/diagram/Whitebox overall system.png.cache
  src/docs/build/docs/images/Sharing a route.png
  src/docs/build/docs/images/Uploading a route.png
  src/docs/build/docs/images/Whitebox overall system.png
  src/docs/build/docs/index.html
  src/docs/diagrams/05-04_whiteboxReact.puml
  src/docs/diagrams/06-02_shareRoute.puml
  src/docs/diagrams/06-03_commentRoute.puml
  src/docs/diagrams/06-04_accessingFriend.puml
  src/docs/diagrams/06_SD_DisplayRoute.puml
  src/docs/diagrams/06_SD_LoadEmail.puml
  src/docs/diagrams/06_SD_LoadFriends.puml
  src/docs/diagrams/06_SD_LoadRoutes.puml
Labels: documentation

#104 Comment routes model
  src/components/layout/comments/Comments.css
  src/components/layout/comments/Comments.js
  src/components/routes/myRoutes/MyRoutes.js
  src/components/routes/myRoutes/MyRoutes.module.css
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/routeDetails/RouteDetails.module.css
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/UploadRoute.module.css
  src/components/routes/uploadRoute/tests/UploadRoute.test.js
  src/components/routes/uploadRoute/uploadButton/UploadButton.js
  src/store/reducers/RouteReducer.js
Labels: development

#109 Storing info
  package-lock.json
  package.json
  src/solid/routes.js
  src/solid/tests/routes.test.js
Labels: development

#113 doc_point8
  package-lock.json
  src/App.test.js
  src/docs/08_concepts.adoc
Labels: documentation

#114 Docs: Fixed typos throughout the documentation.
  src/docs/01_introduction_and_goals.adoc
  src/docs/02_architecture_constraints.adoc
  src/docs/03_system_scope_and_context.adoc
  src/docs/04_solution_strategy.adoc
  src/docs/05_building_block_view.adoc
  src/docs/06_runtime_view.adoc
  src/docs/08_concepts.adoc
  src/docs/09_design_decisions.adoc
  src/docs/10_quality_scenarios.adoc
  src/docs/11_technical_risks.adoc
  src/docs/12_glossary.adoc
Labels: documentation

#122 Typo dashbaord
  src/components/dashboard/Dashboard.js
Labels: bug, development

#118 Documentation cesar
  src/docs/05_building_block_view.adoc
  src/docs/08_concepts.adoc
  src/docs/09_design_decisions.adoc
  src/docs/10_quality_scenarios.adoc
  src/docs/diagrams/03-02_TechnicalContext.puml
  src/docs/diagrams/05-01_whiteboxOverallSystem.puml
  src/docs/diagrams/08-01_Domain.puml
  src/docs/images/10-1QualityTree.png
  src/docs/images/10-QualityTree.png
Labels: documentation

#121 Manual support for the footer
  src/components/layout/footer/Footer.js
Labels: enhancement

#133 Interazionalization edu
  package.json
  src/App.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/tests/Dashboard.test.js
  src/components/layout/comments/Comments.js
  src/components/layout/footer/Footer.js
  src/components/layout/footer/test/Footer.test.js
  src/components/layout/login/Login.js
  src/components/layout/login/tests/Login.test.js
  src/components/layout/modal/tests/Modal.test.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/tests/NavBar.test.js
  src/components/layout/pageNotFound/PageNotFound.js
  src/components/layout/pageNotFound/tests/PageNotFound.test.js
  src/components/layout/settings/Settings.js
  src/components/layout/settings/tests/Settings.test.js
  src/components/layout/slideshow/Slideshow.js
  src/components/layout/slideshow/tests/Slideshow.test.js
  src/components/layout/theme/ThemePicker.js
  src/components/routes/myRoutes/tests/MyRoutes.test.js
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/routeDetails/tests/RouteDetails.test.js
  src/components/routes/routeList/RouteList.js
  src/components/routes/routeList/tests/RouteList.test.js
  src/components/routes/routeSummary/tests/RouteSummary.test.js
  src/components/routes/shareRoute/ShareRoute.js
  src/components/routes/shareRoute/tests/ShareRoute.test.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/tests/UploadRoute.test.js
  src/components/routing/utils/TestingRouter.js
  src/components/user/myProfile/FriendList.js
  src/components/user/myProfile/MyProfile.js
  src/components/user/myProfile/tests/FriendList.test.js
  src/solid/routes.js
  src/solid/tests/routes.test.js
  src/store/actions/localeAction.js
  src/store/actions/tests/LoadActions.test.js
  src/store/actions/tests/LocaleAction.test.js
  src/store/actions/tests/RouteActions.test.js
  src/store/reducers/LocaleReducer.js
  src/store/reducers/RootReducer.js
  src/store/reducers/tests/LoadReducer.test.js
  src/store/reducers/tests/LocaleReducer.test.js
  src/test/App.test.js
  src/utils/locales.js
Labels: development, enhancement

#134 Added an automated script to generate reports of the app
  .gitignore
  execute-load-tests.sh
Labels: testing

#132 License created
  LICENSE
Labels: organizational

#146 Tests fixed. Some more added. Cleaned comments and logs.
  src/solid/parser.js
  src/solid/routes.js
  src/solid/tests/routes.test.js
Labels: development, testing

#141 Trying to fix files rated F by codacy.
  e2e/features/step-definition/myroutes.js
  e2e/features/step-definition/upload.js
  execute-load-tests.sh
Labels: development

#149 Added tests for comments
  src/components/layout/comments/CommentList/CommentList.js
  src/components/layout/comments/CommentList/test/CommentList.test.js
  src/components/layout/comments/comment/Comment.js
  src/components/layout/comments/comment/test/Comment.test.js
  src/components/layout/comments/test/Comments.test.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/uploadButton/UploadButton.js
Labels: testing

#150 Tests
  src/components/routes/routeDetails/tests/RouteDetails.test.js
  src/parser/mockRoute.js
  src/parser/parser.test.js
  src/parser/parser/tests/gpx.test.js
  src/parser/parser/tests/person.test.js
Labels: testing

#135 Readme
  README.md
  e2e/features/login.feature
  package.json
  public/mainApp.png
Labels: documentation, organizational

#152 HotFix: Number of own/shared routes fixed
  src/components/user/myProfile/MyProfile.js
  src/utils/functions.js
  src/utils/tests/functions.test.js
Labels: bug, development

#151 Runtime view updated
  src/docs/06_runtime_view.adoc
  src/docs/diagrams/06-01_uploadRoute.puml
  src/docs/diagrams/06-02_shareRoute.puml
  src/docs/diagrams/06-05_CheckingNotifications.puml
  src/docs/diagrams/06-06_ChangeLanguage.puml
  src/docs/diagrams/06-07_ThemesChange.puml
Labels: documentation

#148 Added JSDoc to routes.js.
  src/solid/routes.js
Labels: development

#154 Handling unconventional pods
  src/solid/routes.js
  src/solid/tests/routes.test.js
Labels: development

#153 Documentation
  src/docs/01_introduction_and_goals.html
  src/docs/05_building_block_view.adoc
  src/docs/08_concepts.adoc
  src/docs/10_quality_scenarios.adoc
  src/docs/11_technical_risks.adoc
  src/docs/diagrams/05-01_whiteboxOverallSystem.puml
  src/docs/diagrams/05-02_whiteboxRedux.puml
  src/docs/diagrams/05-03_whiteboxSolid.puml
  src/docs/diagrams/05-04_whiteboxReact.puml
  src/docs/diagrams/08-01_Domain.puml
  src/docs/images/03-Business Context.png
  src/docs/images/03-TechnicalContext.png
  src/docs/images/05_building_blocks-EN.png
  src/docs/images/08-Crosscutting-Concepts-Structure-EN.png
  src/docs/images/10-1QualityTree.png
  src/docs/images/10-QualityTree.png
  src/parser/test/mockRoute.js
  src/parser/test/parser.test.js
  src/serviceWorker.js
  src/setupTests.js
Labels: documentation
