Repository Arquisoft/viade_en1b, pull requests merged in 2020-05, with the labels that each got.

#159 JsDoc in:
  src/components/dashboard/Dashboard.js
  src/components/dashboard/myMap/MyMap.js
  src/components/layout/footer/Footer.js
  src/components/layout/login/Login.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/theme/ThemePicker.js
  src/components/routes/myRoutes/MyRoutes.js
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/routeList/RouteList.js
  src/components/routes/routeSummary/RouteSummary.js
  src/components/routes/shareRoute/ShareRoute.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/uploadButton/UploadButton.js
  src/components/routing/Routing.js
  src/components/user/myProfile/FriendList.js
  src/components/user/myProfile/MyProfile.js
  src/parser/parser.js
  src/utils/functions.js
Labels: documentation

#157 Solid modifications codacy
  e2e/features/step-definition/myroutes.js
  src/components/dashboard/tests/Dashboard.test.js
  src/components/layout/modal/Modal.css
  src/components/layout/navbar/tests/NavBar.test.js
  src/components/routes/routeList/tests/RouteList.test.js
  src/components/routes/routeSummary/tests/RouteSummary.test.js
  src/components/routes/shareRoute/tests/ShareRoute.test.js
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routes/uploadRoute/uploadButton/UploadButton.js
  src/middlewares/middlewares.js
  src/solid/parser.js
  src/solid/routes.js
  src/store/actions/RouteActions.js
  src/store/reducers/RootReducer.js
  src/store/reducers/RouteReducer.js
  src/store/reducers/tests/RouteReducer.test.js
  src/utils/functions.js
Labels: development

#156 Documentation updates
  src/docs/03_system_scope_and_context.adoc
  src/docs/04_solution_strategy.adoc
  src/docs/05_building_block_view.adoc
  src/docs/diagrams/03-01_BusinessContext.puml
Labels: documentation

#163 Used apis info
  src/docs/03_system_scope_and_context.adoc
  src/docs/diagrams/03-02_TechnicalContext.puml
Labels: documentation

#165 Groups testing
  src/parser/parser/tests/gpx.test.js
  src/solid/parser.js
  src/solid/profileInfo.js
  src/solid/routes.js
  src/solid/tests/profileInfo.test.js
  src/solid/tests/routes.test.js
Labels: testing

#164 Groups
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/tests/NavBar.test.js
  src/components/routes/routeDetails/RouteDetails.js
  src/components/routes/routeDetails/RouteDetails.module.css
  src/components/routes/shareRoute/shareRouteGroup/ShareRouteGroup.js
  src/components/routes/shareRoute/shareRouteGroup/ShareRouteGroup.module.css
  src/components/routes/uploadRoute/UploadRoute.js
  src/components/routing/Routing.js
  src/components/user/myProfile/FriendList.js
  src/components/user/myProfile/grouplist/GroupList.js
  src/components/user/myProfile/grouplist/GroupList.module.css
  src/components/user/myProfile/groups/Groups.js
  src/components/user/myProfile/groups/Groups.module.css
  src/middlewares/middlewares.js
  src/parser/parser/tests/gpx.test.js
  src/solid/parser.js
  src/solid/profileInfo.js
  src/solid/routes.js
  src/solid/tests/profileInfo.test.js
  src/solid/tests/routes.test.js
  src/store/reducers/RouteReducer.js
  src/utils/hooks/hooks.js
  src/utils/locales.js
Labels: development

#169 Sequence diagrams updated
  README.md
  e2e/features/step-definition/upload.js
  src/docs/01_introduction_and_goals.adoc
  src/docs/06_runtime_view.adoc
  src/docs/08_concepts.adoc
  src/docs/diagrams/06_SD_AcceptNotification.puml
  src/docs/diagrams/06_SD_LoadRoutes.puml
  src/docs/diagrams/06_SD_ShareRoutes.puml
  src/docs/diagrams/06_SD_UploadRoute.puml
Labels: documentation

#170 This repository no longer contains a skeleton.
  README.md
  package-lock.json
  src/docs/06_runtime_view.adoc
Labels: documentation
